name: Go

on:
  push:
    branches: [main]

jobs:
  build:
    name: Building Go app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Building
        run: go build ./...
  deploy:
    name: Deploy to Heroku
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.APP_NAME}}
          heroku_email: ${{secrets.EMAIL}}
